"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

@warning - In order to make matplotlib bundle correctly, go find th
  install of the pytz package in your filesystem, add empty __init__.py
  to zoneinfo subdir, move aside pytz/zoneinfo/UTC and create an
  empty pytz/zoneinfo/UTC.py file. Very broken method but it works.
via: http://trac.infodrizzle.org/opendelphos/index.cgi/browser/trunk/src/macsetup.py
"""

import ez_setup
ez_setup.use_setuptools()

import pytz
pytz.zoneinfo = pytz.tzinfo
pytz.zoneinfo.UTC = pytz.UTC

from setuptools import setup

APP = ['init.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
    'iconfile': 'icon.jpg',
    'includes': 'BeautifulSoup,matplotlib',
    'site_packages': True,
    'plist' : 'lumos/Info.plist'}

setup(
    app=APP,
    name="lumos",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
