"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import ez_setup
ez_setup.use_setuptools()

from setuptools import setup

APP = ['lumos.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
    'iconfile': 'icon.jpg',
    'includes': 'BeautifulSoup',
    'site_packages': True,
    'plist' : 'Info.plist'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
